python3 ./StockPricePredictiorSVM.py --sym 'AABA' --shiftamount 1 --DEBUG 0        
python3 ./StockPricePredictiorSVM.py --sym 'AAPL' --shiftamount 1 --DEBUG 0   
python3 ./StockPricePredictiorSVM.py --sym 'AMD' --shiftamount 1 --DEBUG 0        
python3 ./StockPricePredictiorSVM.py --sym 'AMZN' --shiftamount 1 --DEBUG 0   
python3 ./StockPricePredictiorSVM.py --sym 'C' --shiftamount 1 --DEBUG 0        
python3 ./StockPricePredictiorSVM.py --sym 'INTC' --shiftamount 1 --DEBUG 0  
python3 ./StockPricePredictiorSVM.py --sym 'MSFT' --shiftamount 1 --DEBUG 0        
python3 ./StockPricePredictiorSVM.py --sym 'GOOGL' --shiftamount 1 --DEBUG 0  
python3 ./StockPricePredictiorSVM.py --sym 'GOOG' --shiftamount 1 --DEBUG 0   
python3 ./StockPricePredictiorSVM.py --sym 'VZ' --shiftamount 1 --DEBUG 0              
